apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-ca
spec:
  isCA: true
  secretName: kafka-ca-secret
  commonName: kafka.kafka
  dnsNames:
    - kafka.kafka.svc.cluster.local
    - kafka.kafka
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kafka-cluster-issuer
spec:
  ca:
    secretName: kafka-ca-secret
